### ISSUE TITLE
Incorrect LP Sysmon Parameters

### ISSUE THREAD

**Issue by pjabes** [atc-project/atc-data#12]
This issue was raised and resolve by a member of the community through the ATC Slack, however for tracking and remediation purposes I have decided to create a ticket. 

The original request goes like:
> LP_0005_windows_sysmon_network_connection:
We're certainly logging EID 3 in Splunk, but I'm not sure what the LP is referencing when it says "Sysmon event id 3 is disabled by default. It can be enabled by specyfying -n option".
>Trying to figure that out now, because the '-n option' isn't mentioned in sysmon's documentation and isn't mentioned as a flag in sysmon -?.

**Comment by pjabes** [comment]
It was discovered that this is due to the ATC-Data containing Sysmon references from earlier versions.  In particular, the ```-n``` parameter has been deprecated and replaced by the .xml.  I've completed the work required to amend this on a local copy but will look at updating all the LP's related to Sysmon for completeness.

**Comment by yugoslavskiy** [comment]
Thank you very much, once again 🙏
